### ISSUE TITLE
Return a blank response from cPanel

### ISSUE THREAD

**Issue by prodhan** [code4mk/lara-nagad#1]
Hi,
I've installed it on my project and it's working on localhost. But when I upload it into my cPanel server then it's return a blank respone from pay method.

```
$redirectUrl = NagadPayment::tnxID($id)
            ->amount($amount)
            ->getRedirectUrl();
        return response()->json($redirectUrl);
```

**Comment by mostafa6765** [comment]
contact with nagad and whitelisted your IP.

**Comment by mostafa6765** [comment]
> Hi,
> I've installed it on my project and it's working on localhost. But when I upload it into my cPanel server then it's return a blank respone from pay method.
> 
> ```
> $redirectUrl = NagadPayment::tnxID($id)
>             ->amount($amount)
>             ->getRedirectUrl();
>         return response()->json($redirectUrl);
> ```

Install version 1 and follow documentation.
